import type { Metadata } from 'next';

import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import { Header } from '@/modules/Layout/Header';
import { Stack } from '@mui/material';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { AppThemeProvider } from '@/Providers/ThemeProvider';
import { Footer } from '@/modules/Layout/Footer';
export const metadata: Metadata = {
  title: 'Blog da dona Oria',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <AppRouterCacheProvider>
          <AppThemeProvider>
            <Stack
              direction={'column'}
              minHeight={'100vh'}
              justifyContent={'space-between'}
            >
              <Stack direction={'column'}>
                <Header />
                <Stack
                  width={'100%'}
                  height={'100%'}
                  alignItems={'center'}
                  marginY={4}
                  paddingX={2}
                >
                  <Stack width={'100%'} maxWidth={940}>
                    {children}
                  </Stack>
                </Stack>
              </Stack>

              <Footer />
            </Stack>
          </AppThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
